name: NPM CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Build
      run: npm install
    - name: Install VSCE
      run: npm install -g vsce
    - name: Package VSIX
      run: vsce package
